--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "HR"."CITY" 
   (	"CITY_ID" NUMBER(10,0), 
	"PINCODE" NUMBER(6,0), 
	"CITY_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.CITY
SET DEFINE OFF;
Insert into HR.CITY (CITY_ID,PINCODE,CITY_NAME) values (1,625198,'vandalur');
Insert into HR.CITY (CITY_ID,PINCODE,CITY_NAME) values (2,625199,'kelambakkam');
Insert into HR.CITY (CITY_ID,PINCODE,CITY_NAME) values (3,625200,'thambaram');
Insert into HR.CITY (CITY_ID,PINCODE,CITY_NAME) values (4,625201,'perangulathur');
Insert into HR.CITY (CITY_ID,PINCODE,CITY_NAME) values (5,625202,'vadapalani');
--------------------------------------------------------
--  DDL for Index CITY_NAME_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CITY_NAME_UK" ON "HR"."CITY" ("CITY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRN_CITYID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TRN_CITYID_PK" ON "HR"."CITY" ("CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRN_PINCODE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TRN_PINCODE_UK" ON "HR"."CITY" ("PINCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "HR"."CITY" ADD CONSTRAINT "CITY_NAME_UK" UNIQUE ("CITY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."CITY" MODIFY ("PINCODE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CITY" MODIFY ("CITY_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CITY" ADD CONSTRAINT "TRN_CITYID_PK" PRIMARY KEY ("CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."CITY" ADD CONSTRAINT "TRN_PINCODE_UK" UNIQUE ("PINCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
