--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESTAURANT
--------------------------------------------------------

  CREATE TABLE "HR"."RESTAURANT" 
   (	"RESTAURANT_ID" NUMBER(10,0), 
	"RESTAURANT_NAME" VARCHAR2(50 BYTE), 
	"PHONE_NUMBER" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY_ID" NUMBER(10,0), 
	"CATEGORY_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.RESTAURANT
SET DEFINE OFF;
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (1,'anjappar',9862621234,'3/5 cpm nagar,vandalur.',1,4);
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (2,'thalapakkati',9812345679,'2,k.k nagar,thambaram',3,2);
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (3,'saravana bhavan',9876543210,'5,sixth avenue,vandalur',1,1);
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (4,'famous Jigarthanda',9876541239,'anna nagar,kelambakkam',2,3);
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (5,'annaporna',8787676754,'3/612 avenue street kelambakam',1,1);
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (6,'amma mess',9090808090,'13 annai salai vandalur',1,1);
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (7,'amul kulfi',8989707078,'123 karumbukadai vandalur',1,3);
Insert into HR.RESTAURANT (RESTAURANT_ID,RESTAURANT_NAME,PHONE_NUMBER,ADDRESS,CITY_ID,CATEGORY_ID) values (8,'konar kadai',9981234561,'simakkal',2,2);
--------------------------------------------------------
--  DDL for Index RESTUARANT_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."RESTUARANT_ID_PK" ON "HR"."RESTAURANT" ("RESTAURANT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESTPHONE_ID_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."RESTPHONE_ID_UK" ON "HR"."RESTAURANT" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REST_ADDRESS_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."REST_ADDRESS_UK" ON "HR"."RESTAURANT" ("ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RESTAURANT
--------------------------------------------------------

  ALTER TABLE "HR"."RESTAURANT" ADD CONSTRAINT "RESTPHONE_ID_UK" UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."RESTAURANT" ADD CONSTRAINT "RESTUARANT_ID_PK" PRIMARY KEY ("RESTAURANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."RESTAURANT" ADD CONSTRAINT "REST_ADDRESS_UK" UNIQUE ("ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."RESTAURANT" MODIFY ("RESTAURANT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."RESTAURANT" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."RESTAURANT" MODIFY ("ADDRESS" NOT NULL ENABLE);
