--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_CUSTOMERS" 
   (	"ACCOUNT_NUMBER" NUMBER(15,0), 
	"CUSTOMER_NAME" VARCHAR2(50 BYTE), 
	"CUSTOMER_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"PHONE_NUMBER" NUMBER(12,0), 
	"FATHERS_NAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(7 BYTE), 
	"BALANCE" NUMBER(12,2) DEFAULT 0, 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"DOB" DATE, 
	"PERMANENT_ADDRESS" VARCHAR2(250 BYTE), 
	"PERMANENT_CITY" VARCHAR2(25 BYTE), 
	"CURRENT_ADDRESS" VARCHAR2(250 BYTE), 
	"CURRENT_CITY" VARCHAR2(25 BYTE), 
	"STATE" VARCHAR2(25 BYTE), 
	"IFSC_CODE" VARCHAR2(10 BYTE), 
	"FLAG" NUMBER(2,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"MMID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_CUSTOMERS
SET DEFINE OFF;
---------------------------------------------------------
CREATE SEQUENCE Trn_translist_transid_seq01 START WITH 1430 INCREMENT BY 1;
---------------------------------------------------------
Insert into HR.TRN_CUSTOMERS (ACCOUNT_NUMBER,CUSTOMER_NAME,CUSTOMER_ID,EMAIL,PHONE_NUMBER,FATHERS_NAME,GENDER,BALANCE,USERNAME,PASSWORD,DOB,PERMANENT_ADDRESS,PERMANENT_CITY,CURRENT_ADDRESS,CURRENT_CITY,STATE,IFSC_CODE,FLAG,CREATED_DATE,MODIFIED_DATE,MMID) values (620410100000,'Athiselvam',5021,'athitek@rediffmail.com',9042401691,'Nainar','Male',27031.2,'its773','pass123',to_date('11-05-97','DD-MM-RR'),'shanmugam street','shencottai','shanmugam street','shencottai','Tamil nadu','ATEK000138',1,to_timestamp('21-05-19 10:17:00.912000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('21-05-19 10:17:00.912000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),8807651);
Insert into HR.TRN_CUSTOMERS (ACCOUNT_NUMBER,CUSTOMER_NAME,CUSTOMER_ID,EMAIL,PHONE_NUMBER,FATHERS_NAME,GENDER,BALANCE,USERNAME,PASSWORD,DOB,PERMANENT_ADDRESS,PERMANENT_CITY,CURRENT_ADDRESS,CURRENT_CITY,STATE,IFSC_CODE,FLAG,CREATED_DATE,MODIFIED_DATE,MMID) values (620410100022,'rich',5022,'ric@gmail.com',9042401891,'Nainar','Male',15413,'ric123','pass123',to_date('11-05-97','DD-MM-RR'),'shanmugam street','shencottai','shanmugam street','shencottai','Tamil nadu','ATEK000139',1,to_timestamp('21-05-19 10:17:43.790000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('21-05-19 10:17:43.790000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),8807652);
--------------------------------------------------------
--  DDL for Index TRN_CUSTOMER_ACNUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TRN_CUSTOMER_ACNUM_PK" ON "HR"."TRN_CUSTOMERS" ("ACCOUNT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004548
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004548" ON "HR"."TRN_CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004549
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004549" ON "HR"."TRN_CUSTOMERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004550
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004550" ON "HR"."TRN_CUSTOMERS" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004551
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004551" ON "HR"."TRN_CUSTOMERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004552
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004552" ON "HR"."TRN_CUSTOMERS" ("IFSC_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRN_CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("FATHERS_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("DOB" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PERMANENT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PERMANENT_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CURRENT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CURRENT_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("STATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("IFSC_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("IFSC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD CONSTRAINT "TRN_CUSTOMER_ACNUM_PK" PRIMARY KEY ("ACCOUNT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
